export default interface RaceResults {
  created_at: string,
  dnf: boolean,
  fastest_lap: boolean,
  first_name: string,
  game: string,
  human: boolean,
  id: number,
  initials: string,
  last_name: string,
  name: string,
  position: number,
  profile_image: string | null,
  team_name: string,
  user_id: number,
  race_order: number,
  dotd: boolean,
  season_id: number,
  race_distance: number,
  distance: number
}