-- seeds/01_users.sql
-- users seeds
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (1, 'Giordano', 'Temple', 'TEM', 'Toronto', 'Canada', true, '1993-03-11', 'giordano-temple', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (2, 'Cole', 'Reynolds', 'CAR', 'Toronto', 'Canada', true, '1996-10-10', 'cole-reynolds', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (3, 'Ryan', 'Reynolds', 'RCR', 'Toronto', 'Canada', true, '1992-12-05', 'ryan-reynolds', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (4, 'Charles', 'Leclerc', 'LEC', 'Monte Carlo', 'Monaco', false, '1997-10-16', 'charles-leclerc', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (5, 'Lando', 'Norris', 'NOR', 'Bristol', 'United Kingdom', false, '1999-11-13', 'lando-norris', 'united-kingdom');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (6, 'Fernando', 'Alonso', 'ALO', 'Oviedo', 'Spain', false, '1981-07-29', 'fernando-alonso', 'spain');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (7, 'Lance', 'Stroll', 'STR', 'Montreal', 'Canada', false, '1998-10-29', 'lance-stroll', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (8, 'Nicholas', 'Latifi', 'LAT', 'Montreal', 'Canada', false, '1995-06-27', 'nicholas-latifi', 'canada');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (9, 'Alexander', 'Albon', 'ALB', 'London', 'United Kingdom', false, '1996-03-23', 'alex-albon', 'thailand');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (10, 'Logan', 'Sargeant', 'SAR', 'Fort Lauderdale', 'United States', false, '2000-12-31', 'logan-sargeant', 'united-states');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (11, 'Lewis', 'Hamilton', 'HAM', 'Stevenage', 'United Kingdom', false, '1985-01-07', 'lewis-hamilton', 'united-kingdom');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (12, 'George', 'Russel', 'RUS', 'Kings Lynn', 'United Kingdom', false, '1998-02-15', 'george-russel', 'united-kingdom');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (13, 'Max', 'Verstappen', 'VER', 'Hasselt', 'Belgium', false, '1997-09-30', 'max-verstappen', 'netherlands');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (14, 'Sergio', 'Perez', 'PER', 'Guadalajara', 'Mexico', false, '1990-01-26', 'sergio-perez', 'mexico');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (15, 'Valtteri', 'Bottas', 'BOT', 'Nastola', 'Finland', false, '1989-08-28', 'valtteri-bottas', 'finland');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (16, 'Zhou', 'Guanyu', 'ZHO', 'Shanghai', 'China', false, '1999-05-30', 'zhou-guanyu', 'china');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (17, 'Kimi', 'Räikkönen', 'RAI', 'Espoo', 'Finland', false, '1979-10-17', 'kimi-raikkonen', 'finland');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (18, 'Antonio', 'Giovinazzi', 'GIO', 'Martina Franca', 'Italy', false, '1993-12-14', 'antonio-giovinazzi', 'italy');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (20, 'Daniel', 'Ricciardo', 'RIC', 'Perth', 'Australia', false, '1989-07-01', 'daniel-ricciardo');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (21, 'Oscar', 'Piastri', 'PIA', 'Melbourne', 'Australia', false, '2001-04-06', 'oscar-piastri', 'australia');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (22, 'Pierre', 'Gasly', 'GAS', 'Rouen', 'France', false, '1996-02-07', 'pierre-gasly', 'france');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (23, 'Yuki', 'Tsunoda', 'TSU', 'Sagamihara', 'Japan', false, '2000-05-11', 'yuki-tsunoda', 'japan');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (24, 'Nyck', 'de Vries', 'DEV', 'Uitwellingerga', 'Netherlands', false, '1995-02-06', 'nyck-devries', 'netherlands');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (25, 'Daniel', 'Ricciardo', 'RIC', 'Perth', 'Australia', false, '1989-07-01', 'daniel-ricciardo', 'australia');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (26, 'Esteban', 'Ocon', 'OCO', 'Évreux', 'France', false, '1996-09-17', 'esteban-ocon', 'france');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (27, 'Mick', 'Schumacher', 'SCH', 'Genolier', 'Switzerland', false, '1999-03-24', 'mick-schumacher', 'germany');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (28, 'Nikita', 'Mazepin', 'MAZ', 'Moscow', 'Russia', false, '1999-03-02', 'nikita-mazepin', 'russia');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (29, 'Nico', 'Hülkenberg', 'HUL', 'Emmerich', 'Germany', false, '1987-08-19', 'nico-hulkenbgerg', 'germany');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (30, 'Kevin', 'Magnussen', 'MAG', 'Roskilde', 'Denmark', false, '1992-10-05', 'kevin-magnussen', 'denmark');

INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (31, 'Carlos', 'Sainz', 'SAU', 'Madrid', 'Spain', false, '1994-09-01', 'carlos-sainz', 'spain');
INSERT INTO users (id, first_name, last_name, initials, city_of_birth, country_of_birth, human, date_of_birth, profile_image, country_of_representation) VALUES (32, 'Sebastian', 'Vettel', 'VET', 'Heppenheim', 'Germany', false, '1987-07-03', 'sebastian-vettel', 'germany');
